name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v20.14.0]
    env:
      NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
      AUTH_SECRET: ${{secrets.AUTH_SECRET}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: /home/leereal/actions-runner/_work/microfinex-frontend/microfinex-frontend
    - run: npm run build --if-present
      working-directory: /home/leereal/actions-runner/_work/microfinex-frontend/microfinex-frontend
    - name: Change ownership
      run: sudo chown -R $USER:$USER /home/leereal/actions-runner/_work/microfinex-frontend/microfinex-frontend
    - run: sudo pm2 restart 0
      working-directory: /home/leereal/actions-runner/_work/microfinex-frontend/microfinex-frontend
